import { CardKeys } from "../context/shopContext";
import { v4 as uuidv4 } from "uuid";

export const productsStatic: CardKeys[] = [
    {
        id: uuidv4(),
        categoria: "Tecnologia_Games",
        descricao: "",
        destaque: 1,
        estoque: 200,
        image: ["/Carrossel/produto1.webp"],
        price: 1300,
        quantProduct: 5,
        titulo: "Nintendo Switch",
        subTitulo: "Console Nintendo Switch",
        desconto: 25,
      },
  
    {
        id: uuidv4(),
        categoria: "Eletrônico",
        descricao: "",
        destaque: 1,
        estoque: 88,
        image: ["/Carrossel/produto2.webp"],
        price: 3100,
        quantProduct: 5,
        titulo: "Ipad",
        subTitulo: "Apple Ipad Pro",
        desconto: 8,
    },

    {
        id: uuidv4(),
        categoria: "Eletrônico",
        descricao: "",
        destaque: 1,
        estoque: 165,
        image: ["/Carrossel/produto3.webp"],
        price: 1600,
        quantProduct: 3,
        titulo: "Tv 25'",
        subTitulo: "Smart Tv Sansung 25 Polegadas Touch Screen",
        desconto: 25,
    },

    {
        id: uuidv4(),
        image: ["/Carrossel/produto4.webp"],
        titulo: "Playstation 5",
        subTitulo: "Microsoft Playstation 5",
        desconto: 12,
        categoria: "Tecnologia_Games",
        destaque: 1,
        descricao: "",
        price: 3000,
        estoque: 12,
        quantProduct: 5,
    },
    {
        id: uuidv4(),
        image: ["https://images.unsplash.com/photo-1598327105854-c8674faddf79?q=80&w=1631&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "/Produtos/produto1.webp"],
        titulo: "Celular Xiaomi Mi 10",
        subTitulo: "Smartphone Xiaomi Redmi 10 5G Tela 6,58`` 4Gb+128Gb",
        desconto: 0,
        categoria: "Smartphones",
        destaque: 2,
        descricao: "Smartphone 5G Intermediário com câmera de 50MPProcessador Dimensity 700 com 5G e processamento de 7nm | Câmera principal de alta resolução com 50MP | Modo Noturno impressionante | Tela FHD+ AdaptiveSync com 90Hz de taxa de atualização e proteção Corning® Gorilla® Glass | Bateria de 5000mAh (typ) de alta capacidade | Carregamento rápido de 18W",
        price: 2100,
        estoque: 55,
        quantProduct: 4,
    },
    {
        id: uuidv4(),
        image: ["https://images.unsplash.com/photo-1617625802912-cde586faf331?q=80&w=1632&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "/Produtos/produto2.webp"],
        titulo: "Smartwatch K88",
        subTitulo: "Smartwatch K88 Relogio Automático",
        desconto: 0,
        categoria: "Smartphones",
        destaque: 2,
        descricao: "Smartwatch K88 Relogio Automático Tela Touch android 4.0 + ios 8.0 bt 4.2 42.5*36*13mm Função Distância Modo Noturno Sport Levante a mão e acenda a tela",
        price: 1250,
        estoque: 178,
        quantProduct: 8,
    },
    {
        id: uuidv4(),
        image: ["https://images.unsplash.com/photo-1527888477750-6fd34fbfa3f0?q=80&w=1471&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "/Produtos/produto3.webp"],
        titulo: "Nikon Kit D750",
        subTitulo: " Nikon Kit D750 + lente 24-120mm VR DSLR cor",
        desconto: 0,
        categoria: "Eletrônicos",
        destaque: 2,
        descricao: " Nikon Kit D750 + lente 24-120mm VR DSLR cor  preto display de 3.2, obturador tem uma velocidade máxima de: 1/4000 s, modo de auto-foco,  flash integrado",
        price: 2400,
        estoque: 46,
        quantProduct: 4,
    },
    {
        id: uuidv4(),
        image: ["https://images.unsplash.com/photo-1533740566848-5f7d3e04e3d7?q=80&w=1546&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "/Produtos/produto4.webp"],
        titulo: "Macbook air 13",
        subTitulo: "macbook air 13 (2018) / 16gb ram / 512 gb ssd + case anti-impacto + adaptador hdmi",
        desconto: 0,
        categoria: "Eletrônicos",
        destaque: 2,
        descricao: "macbook air 13 (2018) / 16gb ram / 512 gb ssd + case anti-impacto + adaptador hdmi tela de retina 13.3 processador 1.6ghz dual-core intel core i5 gráficos intel uhd graphics 617 1536 mb 16gb ram 512gb ssd",
        price: 3500,
        estoque: 80,
        quantProduct: 5,
    },
    {
        id: uuidv4(),
        image: ["https://images.unsplash.com/photo-1612367990403-73ef3e67bc4f?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "/Produtos/produto5.webp"],
        titulo: "Apple Tablet iPad Pro",
        subTitulo: "Apple Tablet iPad Pro 4G 256GB 11´´",
        desconto: 0,
        categoria: "Smartphone",
        destaque: 2,
        descricao: "Apple Tablet iPad Pro 4G 256GB 11´´ Retroiluminação por LED Multi Touch Screen de 11 polegadas (diagonal) com tecnologia IPS Resolução de 2388 x 1668 a 264 pixels por polegada (ppi) Tecnologia ProMotion",
        price: 7200,
        estoque: 44,
        quantProduct: 2,
    },
    {
        id: uuidv4(),
        image: ["https://images.unsplash.com/photo-1555618568-bdf0a992c512?q=80&w=1470&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D", "/Produtos/produto6.webp"],
        titulo: "Geforce RTX 2080 TI",
        subTitulo: "Placa de vídeo Nvidia MSI Gaming X Trio GeForce RTX 20 Series RTX 2080 Ti",
        desconto: 0,
        categoria: "Tecnologia_Games",
        destaque: 2,
        descricao: "Interface PCI-Express 3 0  Interface de memória: 352bit  Quantidade de núcleos: 4352  Frequência boost do núcleo de 1755MHz  Resolução máxima: 7680x4320  Compatível com DirectX e OpenGL  Requer de 650W de alimentação  Permite a conexão de até 4 monitores simultâneos  Formatos de conexão: HDMI, DisplayPort, USB-C  Ideal para trabalhar em alta velocidade ",
        price: 1730,
        estoque: 133,
        quantProduct: 5,
    },
]