import { CardKeys } from "../context/shopContext";
import { v4 as uuidv4 } from "uuid";

export const productsStatic: CardKeys[] = [
    {
        id: uuidv4(),
        categoria: "Video Game",
        descricao: "",
        destaque: 1,
        estoque: 200,
        image: "/Carrossel/produto1.webp",
        imageDestaque: "/Carrossel/produto1.webp",
        price: 1300,
        quantProduct: 5,
        url: "nintendo-switch",
        imagemCarrossel: "/Carrossel/produto1.webp",
        titulo: "Nintendo Switch",
        subTitulo: "Console Nintendo Switch",
        desconto: 25,
      },
  
    {
        id: uuidv4(),
        categoria: "Eletrônico",
        descricao: "",
        destaque: 1,
        estoque: 88,
        image: "/Carrossel/produto2.webp",
        imageDestaque: "/Carrossel/produto2.webp",
        price: 3100,
        quantProduct: 5,
        url: "ipad-pro",
        imagemCarrossel: "/Carrossel/produto2.webp",
        titulo: "Ipad",
        subTitulo: "Apple Ipad Pro",
        desconto: 8,
    },

    {
        id: uuidv4(),
        categoria: "Eletrônico",
        descricao: "",
        destaque: 1,
        estoque: 165,
        image: "/Carrossel/produto3.webp",
        imageDestaque: "/Carrossel/produto3.webp",
        price: 1600,
        quantProduct: 3,
        url: "tv-sansung-25",
        imagemCarrossel: "/Carrossel/produto3.webp",
        titulo: "Tv 25'",
        subTitulo: "Smart Tv Sansung 25 Polegadas Touch Screen",
        desconto: 25,
    },

    {
        id: uuidv4(),
        categoria: "Video Game",
        descricao: "",
        destaque: 1,
        estoque: 12,
        image: "/Carrossel/produto4.webp",
        imageDestaque: "/Carrossel/produto4.webp",
        price: 3000,
        quantProduct: 5,
        url: "playstation-5",
        imagemCarrossel: "/Carrossel/produto4.webp",
        titulo: "Playstation 5",
        subTitulo: "Microsoft Playstation 5",
        desconto: 12,
    },
    {
        id: uuidv4(),
        url: "xiaomi-mi-10",
        image: "/Produtos/produto1.webp",
        titulo: "Celular Xiomi Mi 10",
        subTitulo: "Smartphone Xiaomi Redmi 10 5G Tela 6,58`` 4Gb+128Gb",
        desconto: 0,
        categoria: "Smartphones",
        destaque: 2,
        imageDestaque: "/Produtos/produto1.webp",
        descricao: "Smartphone 5G Intermediário com câmera de 50MPProcessador Dimensity 700 com 5G e processamento de 7nm | Câmera principal de alta resolução com 50MP | Modo Noturno impressionante | Tela FHD+ AdaptiveSync com 90Hz de taxa de atualização e proteção Corning® Gorilla® Glass | Bateria de 5000mAh (typ) de alta capacidade | Carregamento rápido de 18W",
        price: 2100,
        estoque: 55,
        imagemCarrossel: "/Produtos/produto1.webp",
        quantProduct: 4,
    },
    {
        id: uuidv4(),
        url: "smartwatch-k88",
        image: "/Produtos/produto2.webp",
        titulo: "Smartwatch K88",
        subTitulo: "Smartwatch K88 Relogio Automático",
        desconto: 0,
        categoria: "Smartphones",
        destaque: 2,
        imageDestaque: "/Produtos/produto2.webp",
        descricao: "Smartwatch K88 Relogio Automático Tela Touch android 4.0 + ios 8.0 bt 4.2 42.5*36*13mm Função Distância Modo Noturno Sport Levante a mão e acenda a tela",
        price: 125,
        estoque: 178,
        imagemCarrossel: "/Produtos/produto2.webp",
        quantProduct: 8,
    },
    {
        id: uuidv4(),
        url: "nilkon-d750",
        image: "/Produtos/produto3.webp",
        titulo: "Nikon Kit D750",
        subTitulo: " Nikon Kit D750 + lente 24-120mm VR DSLR cor",
        desconto: 0,
        categoria: "Eletrônicos",
        destaque: 2,
        imageDestaque: "/Produtos/produto3.webp",
        descricao: " Nikon Kit D750 + lente 24-120mm VR DSLR cor  preto display de 3.2, obturador tem uma velocidade máxima de: 1/4000 s, modo de auto-foco,  flash integrado",
        price: 2400,
        estoque: 46,
        imagemCarrossel: "/Produtos/produto3.webp",
        quantProduct: 4,
    },
    {
        id: uuidv4(),
        url: "macbook-air-13",
        image: "/Produtos/produto4.webp",
        titulo: "Macbook air 13",
        subTitulo: "macbook air 13 (2018) / 16gb ram / 512 gb ssd + case anti-impacto + adaptador hdmi",
        desconto: 0,
        categoria: "Eletrônicos",
        destaque: 2,
        imageDestaque: "/Produtos/produto4.webp",
        descricao: "macbook air 13 (2018) / 16gb ram / 512 gb ssd + case anti-impacto + adaptador hdmi tela de retina 13.3 processador 1.6ghz dual-core intel core i5 gráficos intel uhd graphics 617 1536 mb 16gb ram 512gb ssd",
        price: 3500,
        estoque: 80,
        imagemCarrossel: "/Produtos/produto4.webp",
        quantProduct: 5,
    },
    {
        id: uuidv4(),
        url: "ipad-pro",
        image: "/Produtos/produto5.webp",
        titulo: "Apple Tablet iPad Pro",
        subTitulo: "Apple Tablet iPad Pro 4G 256GB 11´´",
        desconto: 0,
        categoria: "Smartphone",
        destaque: 2,
        imageDestaque: "/Produtos/produto5.webp",
        descricao: "Apple Tablet iPad Pro 4G 256GB 11´´ Retroiluminação por LED Multi Touch Screen de 11 polegadas (diagonal) com tecnologia IPS Resolução de 2388 x 1668 a 264 pixels por polegada (ppi) Tecnologia ProMotion",
        price: 7200,
        estoque: 44,
        imagemCarrossel: "/Produtos/produto5.webp",
        quantProduct: 2,
    },
    {
        id: uuidv4(),
        url: "rtx-2080-ti",
        image: "/Produtos/produto6.webp",
        titulo: "Geforce RTX 2080 TI",
        subTitulo: "Placa de vídeo Nvidia MSI Gaming X Trio GeForce RTX 20 Series RTX 2080 Ti",
        desconto: 0,
        categoria: "Smartphone",
        destaque: 2,
        imageDestaque: "/Produtos/produto6.webp",
        descricao: "Interface PCI-Express 3 0  Interface de memória: 352bit  Quantidade de núcleos: 4352  Frequência boost do núcleo de 1755MHz  Resolução máxima: 7680x4320  Compatível com DirectX e OpenGL  Requer de 650W de alimentação  Permite a conexão de até 4 monitores simultâneos  Formatos de conexão: HDMI, DisplayPort, USB-C  Ideal para trabalhar em alta velocidade ",
        price: 1730,
        estoque: 133,
        imagemCarrossel: "/Produtos/produto6.webp",
        quantProduct: 5,
    },
]